version: '3.8'

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: deepauto
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: deepauto123!
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build: .
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db