from enum import Enum as PyEnum

class WorkflowAgentType(PyEnum):
    DATA_COLLECTOR = "DATA_COLLECTOR_AGENT"
    ITINERARY_BUILDER = "ITINERARY_BUILDER_AGENT"
    BUDGET_MANAGER = "BUDGET_MANAGER_AGENT"
    REPORT_GENERATOR = "REPORT_GENERATOR_AGENT"