from enum import Enum as PyEnum

class WorkflowStatus(PyEnum):
    PENDING = "PENDING"
    STARTED = "STARTED"
    DATA_COLLECTOR = "DATA_COLLECTOR"
    ITINERARY_AND_BUDGET = "ITINERARY_AND_BUDGET"
    REPORT_GENERATOR = "REPORT_GENERATOR"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"