from enum import Enum as PyEnum

class WorkflowStatus(PyEnum):
    PENDING = "PENDING"
    STARTED = "STARTED"
    
    DATA_COLLECTOR_START = "DATA_COLLECTOR_START"
    ITINERARY_AND_BUDGET_START = "ITINERARY_AND_BUDGET_START"
    REPORT_GENERATOR_START = "REPORT_GENERATOR_START"
    
    DATA_COLLECTOR_DONE = "DATA_COLLECTOR_DONE"
    ITINERARY_AND_BUDGET_DONE = "ITINERARY_AND_BUDGET_DONE"
    REPORT_GENERATOR_DONE = "REPORT_GENERATOR_DONE"
    
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"